export const shell = `
<div class="app-shell">
  <header class="masthead">
    <div class="brand"><img src="/favicon.svg" alt=""><div><div class="brand-name">GRAVITYBORN</div><div class="brand-subtitle">A GRAVITY ROGUELITE</div></div></div>
    <div class="header-right"><span class="build-tag mono"><span class="live-dot"></span>ALPHA 0.4</span><button class="icon-button" id="help" aria-label="How to play" title="How to play">?</button><button class="icon-button" id="settings" aria-label="Settings" title="Settings">⚙</button><button class="icon-button" id="pause" aria-label="Pause game" title="Pause · Esc" disabled>Ⅱ</button></div>
  </header>
  <main class="workspace">
    <section class="game-column" aria-label="Gravity chamber">
      <div class="section-heading"><h1><span class="live-dot"></span>THE ABANDONED LAB</h1><span class="mono">SECTOR 01 / FIRST CONTACT</span></div>
      <div class="stage" id="stage">
        <canvas id="game" tabindex="0" aria-label="Gravity arena. Move with W A S D. Arrow keys change gravity. Click to place a well. Escape pauses."></canvas>
        <div class="hud"><div class="health-block"><div class="health-label mono"><span>CORE INTEGRITY</span><strong id="health-value">100 / 100</strong></div><div class="health-track" role="progressbar" aria-label="Health" aria-valuemin="0" aria-valuemax="100" aria-valuenow="100"><div class="health-fill" id="health-fill"></div></div></div><div class="hud-right"><div class="hud-stat"><div class="eyebrow">Time</div><strong class="mono" id="timer">00:00</strong></div><div class="hud-stat"><div class="eyebrow">Gravity</div><strong class="mono" id="gravity-name">DOWN</strong></div><span class="gravity-vector" id="gravity-arrow">↓</span></div></div>
        <div class="stage-bottom"><div class="status-chip mono" id="status">6 HOSTILES · CHAMBER SEALED</div><div class="chain-chip mono" id="chain">0× CHAIN</div></div>
        <div class="status-effects mono" id="status-effects" aria-label="Current effects" hidden></div>
        <div class="overlay" id="overlay"><div class="intro-content"><div class="prototype-label mono"><span class="live-dot"></span>THE FIRST EXPERIMENT</div><h2 class="intro-title">THE WEIGHT<span>AWAKENS.</span></h2><p class="intro-description">Turn the entire room into a weapon. Bend gravity, launch heavy objects, and set off impossible chain reactions.</p><div class="intro-actions"><button class="primary-button" id="start">Enter the chamber&nbsp; ↗</button><button class="text-button" id="intro-help">Learn the controls</button></div><div class="intro-footnote mono">ONE CHAMBER. SIX HOSTILES. ENDLESS POSSIBILITIES.</div></div></div>
        <div class="toast" id="toast" role="status" hidden></div>
      </div>
      <div class="controls" id="controls">
        <div class="movement-control"><div class="joystick" id="joystick" role="group" aria-label="Movement joystick"><div class="joystick-knob" id="joystick-knob"></div></div><div class="control-description"><div class="control-caption">Move your core</div><div class="control-hint"><kbd>W A S D</kbd> / drag joystick<br>Stay in motion.</div></div></div>
        <div class="well-control"><button class="well-button" id="well" aria-label="Place gravity well" title="Gravity well · Space or click arena"><span class="well-icon">◎</span><span class="well-key mono" id="well-state">WELL</span></button><div class="control-description"><div class="control-caption">Gravity well</div><div class="control-hint"><kbd>CLICK</kbd> to place · <kbd>SPACE</kbd><br>Pull the room together.</div></div></div>
        <div class="gravity-control"><div class="control-description"><div class="control-caption">Change gravity</div><div class="control-hint"><kbd>ARROW KEYS</kbd><br>Every object follows.</div></div><div class="dpad" aria-label="Gravity direction"><button data-direction="up" aria-label="Gravity up">↑</button><button data-direction="left" aria-label="Gravity left">←</button><span class="dpad-center" aria-hidden="true">✧</span><button data-direction="right" aria-label="Gravity right">→</button><button data-direction="down" class="active" aria-label="Gravity down">↓</button></div></div>
      </div>
    </section>
    <aside class="sidebar">
      <section class="side-section"><h2 class="mono">EXPEDITION / 001</h2><p class="sector-title">Control the force.<br>Change the outcome.</p><p class="sector-description">An abandoned research chamber. Unstable matter. A newly awakened Gravityborn.</p><div class="sector-meta"><span class="small-tag mono">RUINED FACILITY</span><span class="small-tag mono">SANDBOX</span></div></section>
      <section class="side-section"><h2 class="mono">YOUR FIRST EXPERIMENT</h2><div class="objective" id="objective-move"><span class="objective-index">01</span><span>Move your core around the chamber.</span></div><div class="objective" id="objective-flip"><span class="objective-index">02</span><span>Flip gravity. Watch everything follow.</span></div><div class="objective" id="objective-well"><span class="objective-index">03</span><span>Pull objects together with a gravity well.</span></div><div class="objective" id="objective-kill"><span class="objective-index">04</span><span>Let physics eliminate a hostile.</span></div></section>
      <section class="side-section"><h2 class="mono">READ THE ROOM</h2><div class="entity-key"><span class="legend-shape player">●</span>Your core</div><div class="entity-key"><span class="legend-shape enemy">▲</span>Hostile entity</div><div class="entity-key"><span class="legend-shape barrel">!</span>Explosive barrel</div><div class="entity-key"><span class="legend-shape mass"></span>Heavy matter</div></section>
      <div class="sidebar-footer"><button id="debug-open">⌘ &nbsp; Open physics inspector</button></div>
    </aside>
  </main>
  <footer class="footer mono"><span>GRAVITY IS YOUR ONLY WEAPON.</span><span class="desktop-footer">WASD · ARROWS · CLICK / SPACE · ESC</span><span id="performance">PHYSICS ONLINE</span></footer>
</div>
<dialog id="help-dialog" aria-labelledby="help-title"><div class="dialog-header"><h2 id="help-title">Make the room your weapon.</h2><button data-close aria-label="Close instructions">×</button></div><div class="dialog-copy"><p><strong>Move:</strong> W A S D or drag the joystick. Your cyan core can steer against gravity.</p><p><strong>Flip:</strong> Arrow keys or the four direction buttons change gravity for the entire room. Launch rocks and enemies into walls.</p><p><strong>Pull:</strong> Click or tap the arena to create a gravity well. Space places one at your cursor, or ahead of your core. Wells recharge in 5.5 seconds.</p><p><strong>Experiment:</strong> Orange barrels explode on hard impacts. Enemy shots have mass: bend them back into enemies. Combine impacts and explosions into a chain.</p><p><strong>Survive:</strong> Clear all six hostiles. Avoid contact and incoming shots. Escape pauses; R restarts after an attempt ends. Press backtick to open the physics inspector.</p></div></dialog>
<dialog id="settings-dialog" aria-labelledby="settings-title"><div class="dialog-header"><h2 id="settings-title">Settings</h2><button data-close aria-label="Close settings">×</button></div><label class="setting-row"><span>Sound volume<small>Synthesized physics feedback</small></span><input id="volume" type="range" min="0" max="1" step="0.05" aria-label="Sound volume"></label><label class="setting-row"><span>Reduced motion<small>Disable shake and ambient drift</small></span><input id="reduced-motion" type="checkbox"></label><label class="setting-row"><span>Left-handed controls<small>Swap joystick and gravity buttons</small></span><input id="left-handed" type="checkbox"></label><label class="setting-row"><span>Low-power rendering<small>Lower resolution and disable glow</small></span><input id="low-quality" type="checkbox"></label></dialog>
<dialog id="debug-dialog" aria-labelledby="debug-title"><div class="dialog-header"><h2 id="debug-title">Physics inspector</h2><button data-close aria-label="Close physics inspector">×</button></div><p class="dialog-copy">Inspector actions change the current experiment. Close this panel to continue.</p><p class="debug-status mono" id="debug-status"></p><div class="debug-grid"><select id="spawn-kind" aria-label="Entity type"><option>chaser</option><option>shooter</option><option>heavy</option><option>barrel</option><option>crate</option><option>rock</option></select><button id="spawn">Spawn at center</button><button id="debug-well">Create well</button><button id="debug-heal">Restore health</button><button id="debug-step">Step physics frame</button><button id="debug-reset">Reset experiment</button><label><input id="debug-overlay" type="checkbox">Vectors & bounds</label><label>Gravity <input id="gravity-strength" type="range" min="0" max="0.004" step="0.00025" aria-label="Gravity strength" style="width:70px"></label></div></dialog>`;
