import Matter from 'matter-js';
import { expect, it } from 'vitest';
import { Game } from '../src/gameplay/game';
import { ChainTracker } from '../src/gameplay/chains';
import { Expedition } from '../src/progression/expedition';
import { newProfile, readProfile, settleRun } from '../src/progression/profile';
import { freshMastery, masteryLevel } from '../src/progression/mastery';
import { codexView } from '../src/presentation/codex';

it('credits a real wall-impact kill to the ability that supplied its causal chain', () => {
  const game = new Game(false);
  const run = new Expedition(game);
  run.start('mastery');
  run.phase = 'room';
  const enemy = game.world.spawn('chaser', { x: 1100, y: 360 })!;
  enemy.health = 20;
  game.enemies.setElite(enemy, 'inverted');
  const cause = game.createCause('pulse');
  game.markCause(enemy, cause);
  game.start();
  game.gravity.strength = 0;
  Matter.Body.setVelocity(enemy.body, { x: 18, y: 0 });
  for (let i = 0; i < 40 && enemy.alive; i++) game.step();
  expect(enemy.alive).toBe(false);
  expect(run.mastery.pulse.kills).toBe(1);
  expect(run.mastery.pulse.elites).toBe(1);
});
it('counts many parallel effects without allowing unbounded recursive depth or lifetime', () => {
  const chains = new ChainTracker();
  const id = chains.start(0, 'well');
  for (let i = 0; i < 80; i++) chains.extend(id, `impact:${i}`, 1, 1);
  expect(chains.best).toBe(64);
  expect(chains.source(id)).toBe('well');
  expect(chains.extend(id, 'too-deep', 13, 1)).toBe(0);
  chains.touch(id, 19);
  chains.tick(21);
  expect(chains.source(id)).toBe('environment');
});
it('persists discoveries and grants challenge rewards once', () => {
  const profile = newProfile();
  const run = new Expedition(new Game(false));
  run.start('achievements');
  run.phase = 'summary';
  run.bestChain = 20;
  run.discoveries.add('planet:3');
  run.discoveries.add('lore:3');
  run.mastery.pulse = { casts: 50, kills: 100, elites: 1, bosses: 1, chain: 10, wins: 1 };
  expect(settleRun(profile, run)).toBe(true);
  expect(profile.challenges).toContain('chain_twenty');
  expect(profile.equipment.event_horizon).toBe(1);
  expect(masteryLevel(profile.abilityMastery.pulse)).toBe(5);
  const currency = profile.shards;
  expect(settleRun(profile, run)).toBe(false);
  expect(profile.shards).toBe(currency);
  expect(readProfile(profile)).toEqual(profile);
  const codex = codexView(profile);
  expect(codex).toContain('Kepler Remnant');
  expect(codex).toContain('The last station');
  expect(codex).not.toContain('Aster Foundry');
});
it('mastery milestones require actual combat achievements beyond cast count', () => {
  const progress = freshMastery();
  progress.casts = 10000;
  expect(masteryLevel(progress)).toBe(1);
  progress.kills = 100;
  expect(masteryLevel(progress)).toBe(2);
  progress.elites = 1;
  expect(masteryLevel(progress)).toBe(3);
  progress.chain = 10;
  expect(masteryLevel(progress)).toBe(4);
  progress.wins = 1;
  expect(masteryLevel(progress)).toBe(5);
});
