import { expect, it } from 'vitest';
import { Game } from '../src/gameplay/game';
import { abilityById } from '../src/content/abilities';
import Matter from 'matter-js';

it('gravity chain circulates signed response through eligible targets and expires independently', () => {
  const game = new Game(false);
  const targets = [700, 740, 780].map((x) => game.world.spawn('crate', { x, y: 400 })!);
  const original = [0.5, -1, 2];
  targets.forEach((entity, index) => {
    entity.gravityScale = original[index];
  });
  const phased = game.world.spawn('crate', { x: 810, y: 400 })!;
  phased.gravityFactors.set('phase', 0);
  const locked = game.world.spawn('crate', { x: 680, y: 400 })!;
  Matter.Body.setStatic(locked.body, true);
  game.abilities.learn('chain');
  game.start();
  expect(game.castAbility('chain', targets[0].body.position)).toBe(true);
  expect(targets.map((entity) => entity.gravityScale)).toEqual([2, 0.5, -1]);
  expect(new Set(targets.map((entity) => entity.chainId)).size).toBe(1);
  expect(phased.chainId).toBeNull();
  expect(locked.chainId).toBeNull();
  game.abilities.cooldowns.clear();
  expect(game.castAbility('chain', targets[0].body.position)).toBe(false);
  targets[2].gravityFactors.set('parasite:test', -1.8);
  game.time = 5;
  game.abilities.tick(0);
  expect(targets.map((entity) => entity.gravityScale)).toEqual([0.5, -1, -3.6]);
});

it('one eligible chain target consumes neither energy nor a causal chain', () => {
  const game = new Game(false);
  const target = game.world.spawn('crate', { x: 700, y: 400 })!;
  game.abilities.learn('chain');
  game.start();
  let causes = 0;
  game.events.on('chainStarted', () => causes++);
  expect(game.castAbility('chain', target.body.position)).toBe(false);
  expect(game.abilities.energy).toBe(100);
  expect(causes).toBe(0);
});

it('phase exit preserves theft and inversion regardless of effect expiration order', () => {
  const game = new Game(false);
  const target = game.world.spawn('phase', { x: 700, y: 400 })!;
  game.enemies.setElite(target, 'inverted');
  game.abilities.learn('theft');
  game.start();
  game.castAbility('theft', target.body.position);
  const stolenResponse = target.gravityScale;
  expect(stolenResponse).toBeLessThan(0);
  expect(stolenResponse).toBeGreaterThan(-1);
  target.life = 2.1;
  game.enemies.update(target);
  expect(target.gravityScale).toBe(0);
  target.life = 4.1;
  game.enemies.update(target);
  expect(target.gravityScale).toBe(stolenResponse);
  target.life = 6.1;
  game.enemies.update(target);
  game.time = 20;
  game.abilities.tick(0);
  expect(target.gravityScale).toBe(0);
  target.life = 8.1;
  game.enemies.update(target);
  expect(target.gravityScale).toBe(-1);
});
it('multiple parasites clean up only their own factors while theft remains active', () => {
  const game = new Game(false);
  const target = game.world.spawn('heavy', { x: 700, y: 400 })!;
  const first = game.world.spawn('parasite', { x: 750, y: 400 })!;
  const second = game.world.spawn('parasite', { x: 800, y: 400 })!;
  game.enemies.update(first);
  game.enemies.update(second);
  expect(target.gravityScale).toBeCloseTo(1.8 * 1.8);
  game.abilities.learn('theft');
  game.start();
  game.castAbility('theft', target.body.position);
  const factor = target.gravityFactors.get('theft')!;
  game.applyDamage(first, 85, game.createCause());
  expect(target.gravityScale).toBeCloseTo(-1.8 * factor);
  game.applyDamage(second, 85, game.createCause());
  expect(target.gravityScale).toBeCloseTo(factor);
  game.time = 20;
  game.abilities.tick(0);
  expect(target.gravityScale).toBe(1);
});
it('projectile reuse clears response factors as well as base gravity', () => {
  const game = new Game(false);
  const projectile = game.world.spawn('projectile', { x: 700, y: 400 })!;
  projectile.gravityFactors.set('phase', 0);
  projectile.gravityScale = -2;
  game.world.remove(projectile);
  const reused = game.world.spawn('projectile', { x: 800, y: 400 })!;
  expect(reused).toBe(projectile);
  expect(reused.gravityScale).toBe(1);
  expect(reused.gravityFactors.size).toBe(0);
});
it('an expired lock on a recycled projectile cannot unlock its new incarnation', () => {
  const game = new Game(false);
  const first = game.world.spawn('projectile', { x: 700, y: 400 })!;
  game.abilities.learn('lock');
  game.start();
  expect(game.castAbility('lock', first.body.position)).toBe(true);
  expect(first.body.isStatic).toBe(true);
  game.world.remove(first);
  const second = game.world.spawn('projectile', { x: 900, y: 400 })!;
  expect(second).toBe(first);
  expect(second.body.isStatic).toBe(false);
  expect(second.body.mass).toBeCloseTo(second.definition.mass);
  game.time = 1;
  game.abilities.cooldowns.clear();
  game.castAbility('lock', second.body.position);
  expect(second.body.isStatic).toBe(true);
  game.time = abilityById.get('lock')!.duration + 0.1;
  game.abilities.tick(0);
  expect(second.body.isStatic).toBe(true);
  game.time += 1;
  game.abilities.tick(0);
  expect(second.body.isStatic).toBe(false);
});
it('gravity transfer exchanges signed response and removes only its own factor on expiry', () => {
  const game = new Game(false);
  const a = game.world.spawn('crate', { x: 700, y: 400 })!;
  const b = game.world.spawn('floater', { x: 740, y: 400 })!;
  a.gravityScale = -1;
  const aResponse = a.gravityScale * a.definition.gravityResponse;
  const bResponse = b.gravityScale * b.definition.gravityResponse;
  game.abilities.learn('transfer');
  game.start();
  expect(game.castAbility('transfer', a.body.position)).toBe(true);
  expect(a.gravityScale * a.definition.gravityResponse).toBeCloseTo(bResponse);
  expect(b.gravityScale * b.definition.gravityResponse).toBeCloseTo(aResponse);
  b.gravityFactors.set('parasite:external', -1.8);
  game.abilities.cooldowns.clear();
  expect(game.castAbility('transfer', a.body.position)).toBe(false);
  game.time = 5;
  game.abilities.tick(0);
  expect(a.gravityScale).toBe(-1);
  expect(b.gravityScale).toBe(-1.8);
  expect(b.gravityFactors.size).toBe(1);
});
