import { expect, it } from 'vitest';
import { Game } from '../src/gameplay/game';
import { abilityById } from '../src/content/abilities';

it('phase exit preserves theft and inversion regardless of effect expiration order', () => {
  const game = new Game(false);
  const target = game.world.spawn('phase', { x: 700, y: 400 })!;
  game.enemies.setElite(target, 'inverted');
  game.abilities.learn('theft');
  game.start();
  game.castAbility('theft', target.body.position);
  const stolenResponse = target.gravityScale;
  expect(stolenResponse).toBeLessThan(0);
  expect(stolenResponse).toBeGreaterThan(-1);
  target.life = 2.1;
  game.enemies.update(target);
  expect(target.gravityScale).toBe(0);
  target.life = 4.1;
  game.enemies.update(target);
  expect(target.gravityScale).toBe(stolenResponse);
  target.life = 6.1;
  game.enemies.update(target);
  game.time = 20;
  game.abilities.tick(0);
  expect(target.gravityScale).toBe(0);
  target.life = 8.1;
  game.enemies.update(target);
  expect(target.gravityScale).toBe(-1);
});
it('multiple parasites clean up only their own factors while theft remains active', () => {
  const game = new Game(false);
  const target = game.world.spawn('heavy', { x: 700, y: 400 })!;
  const first = game.world.spawn('parasite', { x: 750, y: 400 })!;
  const second = game.world.spawn('parasite', { x: 800, y: 400 })!;
  game.enemies.update(first);
  game.enemies.update(second);
  expect(target.gravityScale).toBeCloseTo(1.8 * 1.8);
  game.abilities.learn('theft');
  game.start();
  game.castAbility('theft', target.body.position);
  const factor = target.gravityFactors.get('theft')!;
  game.applyDamage(first, 85, game.createCause());
  expect(target.gravityScale).toBeCloseTo(-1.8 * factor);
  game.applyDamage(second, 85, game.createCause());
  expect(target.gravityScale).toBeCloseTo(factor);
  game.time = 20;
  game.abilities.tick(0);
  expect(target.gravityScale).toBe(1);
});
it('projectile reuse clears response factors as well as base gravity', () => {
  const game = new Game(false);
  const projectile = game.world.spawn('projectile', { x: 700, y: 400 })!;
  projectile.gravityFactors.set('phase', 0);
  projectile.gravityScale = -2;
  game.world.remove(projectile);
  const reused = game.world.spawn('projectile', { x: 800, y: 400 })!;
  expect(reused).toBe(projectile);
  expect(reused.gravityScale).toBe(1);
  expect(reused.gravityFactors.size).toBe(0);
});
it('an expired lock on a recycled projectile cannot unlock its new incarnation', () => {
  const game = new Game(false);
  const first = game.world.spawn('projectile', { x: 700, y: 400 })!;
  game.abilities.learn('lock');
  game.start();
  expect(game.castAbility('lock', first.body.position)).toBe(true);
  expect(first.body.isStatic).toBe(true);
  game.world.remove(first);
  const second = game.world.spawn('projectile', { x: 900, y: 400 })!;
  expect(second).toBe(first);
  expect(second.body.isStatic).toBe(false);
  expect(second.body.mass).toBeCloseTo(second.definition.mass);
  game.time = 1;
  game.abilities.cooldowns.clear();
  game.castAbility('lock', second.body.position);
  expect(second.body.isStatic).toBe(true);
  game.time = abilityById.get('lock')!.duration + 0.1;
  game.abilities.tick(0);
  expect(second.body.isStatic).toBe(true);
  game.time += 1;
  game.abilities.tick(0);
  expect(second.body.isStatic).toBe(false);
});
