import type { AbilityDefinition } from './abilities';

export const advancedAbilities: AbilityDefinition[] = [
  {
    id: 'polarity',
    name: 'Polarity Curse',
    rarity: 'rare',
    description:
      'Invert the signed gravity response of movable bodies near your aim for four seconds. Already inverted bodies turn normal; phased bodies remain phased.',
    tags: ['Gravity', 'Chaos', 'Control'],
    effect: 'response',
    energy: 24,
    cooldown: 7,
    radius: 180,
    strength: -1,
    duration: 4,
    target: 'point',
    maxLevel: 3,
    feedback: { color: '#eeb3ff', startFrequency: 360, endFrequency: 90 },
  },
  {
    id: 'phase_pocket',
    name: 'Phase Pocket',
    rarity: 'epic',
    description:
      'Temporarily remove gravity response from movable bodies near your aim. Their momentum survives and the effect travels with each body.',
    tags: ['Void', 'Defense', 'Control'],
    effect: 'response',
    energy: 30,
    cooldown: 9,
    radius: 150,
    strength: 0,
    duration: 3,
    target: 'point',
    maxLevel: 3,
    feedback: { color: '#c3c7ff', startFrequency: 220, endFrequency: 60 },
  },
  {
    id: 'resonance_mark',
    name: 'Resonance Mark',
    rarity: 'common',
    description:
      'Double nearby bodies’ response to every gravity source for five seconds. Combine with a well or inversion; anchors remain gravity-resistant.',
    tags: ['Gravity', 'Mass', 'Control'],
    effect: 'response',
    energy: 18,
    cooldown: 6,
    radius: 160,
    strength: 2,
    duration: 5,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'kinetic_brake',
    name: 'Kinetic Brake',
    rarity: 'common',
    description:
      'Remove 85% of nearby bodies’ velocity without stopping gravity. Slow a volley or reduce dangerous debris before redirecting it.',
    tags: ['Velocity', 'Projectile', 'Defense'],
    effect: 'impulse',
    energy: 16,
    cooldown: 4,
    radius: 190,
    strength: 0,
    duration: 0,
    target: 'point',
    maxLevel: 3,
    evolution: 'counterthrow',
    parameters: { momentumScale: 0.15 },
  },
  {
    id: 'counterthrow',
    name: 'Counterthrow',
    rarity: 'epic',
    description:
      'Reverse nearby bodies’ momentum at 120% speed, returning moving debris and shots along their approach.',
    tags: ['Velocity', 'Projectile', 'Impact'],
    effect: 'impulse',
    energy: 30,
    cooldown: 7,
    radius: 240,
    strength: 0,
    duration: 0,
    target: 'point',
    maxLevel: 3,
    parameters: { momentumScale: -1.2 },
  },
  {
    id: 'tether',
    name: 'Gravity Tether',
    rarity: 'rare',
    description:
      'Join the two nearest movable bodies with a short-lived physical spring. Launch one to drag the other into its path.',
    tags: ['Gravity', 'Control', 'Impact'],
    effect: 'tether',
    energy: 24,
    cooldown: 7,
    radius: 240,
    strength: 0.015,
    duration: 4,
    target: 'point',
    maxLevel: 3,
    evolution: 'constellation',
    parameters: { chainTargets: 2, tetherLength: 70 },
    feedback: { color: '#8effdc', startFrequency: 160, endFrequency: 290 },
  },
  {
    id: 'constellation',
    name: 'Constellation',
    rarity: 'legendary',
    description:
      'Link up to four nearby bodies into a physical chain. Gravity on each body pulls the entire constellation until the links expire or break on death.',
    tags: ['Gravity', 'Control', 'Impact', 'Orbit'],
    effect: 'tether',
    energy: 42,
    cooldown: 12,
    radius: 300,
    strength: 0.012,
    duration: 6,
    target: 'point',
    maxLevel: 3,
    parameters: { chainTargets: 4, tetherLength: 90 },
    feedback: { color: '#8effdc', startFrequency: 140, endFrequency: 420 },
  },
];
