export const challenges = [
  {
    id: 'first_hundred',
    name: 'Matter Remembers',
    description: 'Defeat 100 enemies through gravity combat.',
    metric: 'kills',
    target: 100,
    shards: 30,
    research: 4,
  },
  {
    id: 'chain_twenty',
    name: 'The Impossible Cascade',
    description: 'Create a causal chain with 20 distinct effects.',
    metric: 'chain',
    target: 20,
    shards: 50,
    research: 6,
    equipment: 'event_horizon',
  },
  {
    id: 'return_fire',
    name: 'Return to Sender',
    description: 'Defeat 25 enemies with redirected projectiles.',
    metric: 'redirected',
    target: 25,
    shards: 30,
    research: 4,
  },
  {
    id: 'guardian',
    name: 'Worldbreaker',
    description: 'Defeat five guardians.',
    metric: 'bosses',
    target: 5,
    shards: 40,
    research: 5,
  },
  {
    id: 'weightless',
    name: 'Between Falling',
    description: 'Spend five cumulative minutes inside zero gravity during completed rooms.',
    metric: 'zeroSeconds',
    target: 300,
    shards: 25,
    research: 4,
  },
  {
    id: 'elite_hunter',
    name: 'Rule Breaker',
    description: 'Defeat ten elites.',
    metric: 'elites',
    target: 10,
    shards: 25,
    research: 4,
  },
  {
    id: 'well_guardian',
    name: 'A Center of Your Own',
    description: 'Defeat a guardian with a chain originating from a gravity well.',
    metric: 'wellBosses',
    target: 1,
    shards: 40,
    research: 5,
    equipment: 'phoenix_reactor',
  },
  {
    id: 'orbital_victory',
    name: 'Small Solar System',
    description: 'Win an expedition with at least 75% of your kills attributed to orbital powers.',
    metric: 'orbitalWins',
    target: 1,
    shards: 50,
    research: 6,
  },
] as const;
