import type { AbilityDefinition } from './abilities';

function field(
  definition: Omit<AbilityDefinition, 'effect' | 'maxLevel' | 'target'> & {
    target?: AbilityDefinition['target'];
  },
): AbilityDefinition {
  return { effect: 'field', maxLevel: 3, target: 'point', ...definition };
}

export const dynamicFieldAbilities: AbilityDefinition[] = [
  field({
    id: 'pulsing_well',
    name: 'Pulsing Well',
    rarity: 'rare',
    description:
      'Alternate attraction and repulsion through a two-second cycle. Gather matter on one half of the cycle and launch it on the next.',
    tags: ['Gravity', 'Chaos', 'Impact'],
    mode: 'radial',
    energy: 28,
    cooldown: 9,
    radius: 220,
    strength: 0.006,
    duration: 6,
    parameters: { strengthPeriod: 2 },
  }),
  field({
    id: 'zero_bloom',
    name: 'Zero Bloom',
    rarity: 'rare',
    description:
      'Grow a stationary zero-gravity pocket from a small seed to a wide shelter over five seconds. Momentum remains intact as the edge reaches each body.',
    tags: ['Void', 'Control', 'Defense'],
    mode: 'zero',
    energy: 25,
    cooldown: 8,
    radius: 270,
    strength: 1,
    duration: 5,
    parameters: { radiusStart: 0.1, radiusEnd: 1 },
  }),
  field({
    id: 'expanding_repulsion',
    name: 'Expanding Repulsion',
    rarity: 'rare',
    description:
      'A repulsion field grows outward over three seconds. Nearby matter launches first, while more distant bodies join the expanding push.',
    tags: ['Gravity', 'Impact', 'Control'],
    mode: 'radial',
    energy: 28,
    cooldown: 8,
    radius: 340,
    strength: -0.008,
    duration: 3,
    parameters: { radiusStart: 0.12, radiusEnd: 1 },
  }),
  field({
    id: 'contracting_well',
    name: 'Contracting Well',
    rarity: 'rare',
    description:
      'A wide attraction field narrows over five seconds. Matter that reaches the center stays captured while objects left outside the shrinking edge break free.',
    tags: ['Gravity', 'Compression', 'Control'],
    mode: 'radial',
    energy: 30,
    cooldown: 9,
    radius: 350,
    strength: 0.007,
    duration: 5,
    parameters: { radiusStart: 1, radiusEnd: 0.15 },
  }),
  field({
    id: 'dipole',
    name: 'Dipole Gate',
    rarity: 'epic',
    description:
      'Place an attraction source ahead of your aim point and a repulsion source behind it. Their overlapping fields carry matter through the gap.',
    tags: ['Gravity', 'Velocity', 'Control'],
    mode: 'radial',
    energy: 34,
    cooldown: 10,
    radius: 190,
    strength: 0.005,
    duration: 5,
    parameters: { fieldCount: 2, fieldOffset: 100, alternatePolarity: true },
  }),
  field({
    id: 'quadrupole',
    name: 'Quadrupole',
    rarity: 'legendary',
    description:
      'Arrange four alternating attraction and repulsion sources around your aim. Matter enters along the repulsion axis and gathers at the two attracting poles.',
    tags: ['Gravity', 'Chaos', 'Control'],
    mode: 'radial',
    energy: 48,
    cooldown: 14,
    radius: 150,
    strength: 0.0045,
    duration: 6,
    parameters: { fieldCount: 4, fieldOffset: 130, alternatePolarity: true },
  }),
  field({
    id: 'sweeping_current',
    name: 'Sweeping Current',
    rarity: 'rare',
    description:
      'Rotate the direction of a local force zone through a full turn every two seconds. Time entry to carry matter toward a chosen wall.',
    tags: ['Gravity', 'Velocity', 'Chaos'],
    mode: 'directional',
    energy: 28,
    cooldown: 8,
    radius: 170,
    strength: 0.0045,
    duration: 4,
    parameters: { directionSpeed: Math.PI, falloff: 'constant' },
  }),
  field({
    id: 'orbital_lantern',
    name: 'Orbital Lantern',
    rarity: 'epic',
    description:
      'An attraction source circles your core at a fixed distance for six seconds. Move your core to carry the entire orbit through the chamber.',
    tags: ['Gravity', 'Orbit', 'Movement'],
    mode: 'radial',
    target: 'player',
    energy: 32,
    cooldown: 10,
    radius: 160,
    strength: 0.005,
    duration: 6,
    parameters: { fieldOffset: 110, orbitSpeed: 2 },
  }),
  field({
    id: 'metal_satellites',
    name: 'Metal Satellites',
    rarity: 'epic',
    description:
      'Two magnetic sources circle your aim point and pull only metal. Send scrap around their path while stone crosses the pattern unaffected.',
    tags: ['Gravity', 'Orbit', 'Control'],
    mode: 'radial',
    energy: 36,
    cooldown: 11,
    radius: 155,
    strength: 0.006,
    duration: 6,
    parameters: { fieldCount: 2, fieldOffset: 100, orbitSpeed: -2, affects: ['metal'] },
  }),
  field({
    id: 'return_wave',
    name: 'Returning Wave',
    rarity: 'rare',
    description:
      'A force zone travels along your aim and then returns to its origin over four seconds. Its force always points outward, so the returning zone can collect late-arriving matter.',
    tags: ['Gravity', 'Velocity', 'Projectile'],
    mode: 'directional',
    target: 'player',
    energy: 30,
    cooldown: 9,
    radius: 100,
    strength: 0.006,
    duration: 4,
    parameters: { travelSpeed: 180, returning: true, falloff: 'constant' },
  }),
  field({
    id: 'spiral_bloom',
    name: 'Spiral Bloom',
    rarity: 'epic',
    description:
      'A small vortex grows into a wide orbital trap over five seconds. New debris enters the orbit as its influence expands.',
    tags: ['Gravity', 'Orbit', 'Control'],
    mode: 'vortex',
    energy: 34,
    cooldown: 10,
    radius: 300,
    strength: 0.005,
    duration: 5,
    parameters: { radiusStart: 0.1, radiusEnd: 1 },
  }),
  field({
    id: 'gravity_brand',
    name: 'Gravity Brand',
    rarity: 'rare',
    description:
      'Attach an attraction source to the nearest movable body at your aim. The source follows its carrier and ends when the carrier disappears.',
    tags: ['Gravity', 'Control', 'Mass'],
    mode: 'radial',
    energy: 24,
    cooldown: 7,
    radius: 200,
    strength: 0.005,
    duration: 6,
    parameters: { attach: true },
  }),
  field({
    id: 'null_brand',
    name: 'Null Brand',
    rarity: 'rare',
    description:
      'Attach a zero-gravity pocket to nearby movable matter. Launch the carrier to transport a gravity-free corridor through the room.',
    tags: ['Void', 'Control', 'Movement'],
    mode: 'zero',
    energy: 28,
    cooldown: 8,
    radius: 145,
    strength: 1,
    duration: 5,
    parameters: { attach: true },
  }),
  field({
    id: 'orbit_brand',
    name: 'Orbit Brand',
    rarity: 'epic',
    description:
      'Attach a vortex to nearby movable matter. Its orbit travels with the carrier, making a hostile or a loose prop the center of your next attack.',
    tags: ['Gravity', 'Orbit', 'Control'],
    mode: 'vortex',
    energy: 32,
    cooldown: 10,
    radius: 220,
    strength: 0.0055,
    duration: 6,
    parameters: { attach: true },
  }),
];
