import type { AbilityDefinition } from './abilities';

export const kineticAbilities: AbilityDefinition[] = [
  {
    id: 'densify',
    name: 'Densify',
    rarity: 'rare',
    description:
      'Triple nearby bodies’ mass for five seconds. Heavy ammunition hits harder but resists your launch impulses.',
    tags: ['Mass', 'Impact', 'Control'],
    effect: 'mass',
    energy: 26,
    cooldown: 8,
    radius: 170,
    strength: 3,
    duration: 5,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'featherweight',
    name: 'Featherweight',
    rarity: 'common',
    description:
      'Reduce nearby bodies to one quarter of their mass for four seconds. Launch them easily, then let their weight return before impact.',
    tags: ['Mass', 'Velocity', 'Control'],
    effect: 'mass',
    energy: 20,
    cooldown: 6,
    radius: 190,
    strength: 0.25,
    duration: 4,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'iron_core',
    name: 'Iron Core',
    rarity: 'rare',
    description:
      'Triple your core’s mass for four seconds. Ram loose matter with greater weight while keeping your usual gravity response.',
    tags: ['Mass', 'Impact', 'Defense'],
    effect: 'mass',
    energy: 25,
    cooldown: 9,
    radius: 1,
    strength: 3,
    duration: 4,
    target: 'player',
    maxLevel: 3,
    parameters: { selfOnly: true },
  },
  {
    id: 'paper_shots',
    name: 'Paper Shots',
    rarity: 'rare',
    description:
      'Reduce nearby projectiles to one tenth of their mass for five seconds. Weak impulses can now redirect the volley; projectile damage is unchanged.',
    tags: ['Mass', 'Projectile', 'Control'],
    effect: 'mass',
    energy: 18,
    cooldown: 6,
    radius: 230,
    strength: 0.1,
    duration: 5,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['Projectile'] },
  },
  {
    id: 'orbital_strike',
    name: 'Orbital Strike',
    rarity: 'epic',
    description:
      'Kick nearby matter tangentially around your aim. Preserve its incoming velocity to bend a fall into a dangerous sweeping arc.',
    tags: ['Orbit', 'Impact', 'Velocity'],
    effect: 'orbit_impulse',
    energy: 28,
    cooldown: 7,
    radius: 230,
    strength: 14,
    duration: 0,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'counter_orbit',
    name: 'Counter Orbit',
    rarity: 'rare',
    description:
      'Erase nearby momentum, then launch matter counterclockwise around your aim. A precise reset trades incoming speed for a predictable arc.',
    tags: ['Orbit', 'Control', 'Velocity'],
    effect: 'orbit_impulse',
    energy: 30,
    cooldown: 8,
    radius: 190,
    strength: -13,
    duration: 0,
    target: 'point',
    maxLevel: 3,
    parameters: { momentumScale: 0 },
  },
  {
    id: 'quarter_turn',
    name: 'Quarter Turn',
    rarity: 'common',
    description:
      'Turn nearby velocities clockwise by ninety degrees without changing speed. Falling debris becomes a horizontal barrage.',
    tags: ['Velocity', 'Control', 'Impact'],
    effect: 'vector_turn',
    energy: 18,
    cooldown: 5,
    radius: 190,
    strength: Math.PI / 2,
    duration: 0,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'shot_turn',
    name: 'Shot Turn',
    rarity: 'rare',
    description:
      'Turn nearby projectiles counterclockwise by ninety degrees. Other matter keeps its course, letting you redirect a volley through a crowded room.',
    tags: ['Velocity', 'Projectile', 'Control'],
    effect: 'vector_turn',
    energy: 16,
    cooldown: 4,
    radius: 260,
    strength: -Math.PI / 2,
    duration: 0,
    target: 'player',
    maxLevel: 3,
    parameters: { affects: ['Projectile'] },
  },
  {
    id: 'vector_conductor',
    name: 'Vector Conductor',
    rarity: 'epic',
    description:
      'Align moving matter around your core with your aim, preserving each body’s speed. Stationary matter stays still.',
    tags: ['Velocity', 'Control', 'Impact'],
    effect: 'steer',
    energy: 32,
    cooldown: 8,
    radius: 260,
    strength: 1,
    duration: 0,
    target: 'player',
    maxLevel: 3,
  },
  {
    id: 'volley_conductor',
    name: 'Volley Conductor',
    rarity: 'rare',
    description:
      'Aim nearby moving projectiles in one direction while preserving their speed. Redirected shots can strike their former owners.',
    tags: ['Velocity', 'Projectile', 'Control'],
    effect: 'steer',
    energy: 22,
    cooldown: 6,
    radius: 300,
    strength: 1,
    duration: 0,
    target: 'player',
    maxLevel: 3,
    parameters: { affects: ['Projectile'] },
  },
];
