import type { AbilityDefinition } from './abilities';

export const specialistAbilities: AbilityDefinition[] = [
  {
    id: 'magnet_well',
    name: 'Magnet Well',
    rarity: 'common',
    tags: ['Gravity', 'Control', 'Metal'],
    description:
      'Attract metal matter toward a point while leaving stone, crystal and your core untouched. Gather a selective ammunition pile.',
    effect: 'field',
    mode: 'radial',
    energy: 16,
    cooldown: 5,
    radius: 280,
    strength: 0.007,
    duration: 4,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['metal'] },
    evolution: 'scrap_cyclone',
  },
  {
    id: 'scrap_cyclone',
    name: 'Scrap Cyclone',
    rarity: 'rare',
    tags: ['Gravity', 'Orbit', 'Metal'],
    description:
      'Spin metal matter into an orbit without bending nonmetal bodies. Metal enemies and barrels become selective orbital weapons.',
    effect: 'field',
    mode: 'vortex',
    energy: 26,
    cooldown: 8,
    radius: 280,
    strength: 0.006,
    duration: 5,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['metal'] },
  },
  {
    id: 'stonebreaker',
    name: 'Stonebreaker Rail',
    rarity: 'rare',
    tags: ['Gravity', 'Projectile', 'Mass'],
    description:
      'Accelerate only stone matter along your aiming line. Launch rocks through a mixed crowd without pulling the crowd itself.',
    effect: 'beam',
    energy: 16,
    cooldown: 4,
    radius: 600,
    strength: 15,
    duration: 0,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['stone'] },
  },
  {
    id: 'crystal_surge',
    name: 'Crystal Surge',
    rarity: 'common',
    tags: ['Gravity', 'Velocity', 'Crystal'],
    description:
      'A traveling force front carries crystals along your aim. Other materials pass through the front unchanged.',
    effect: 'field',
    mode: 'directional',
    energy: 16,
    cooldown: 5,
    radius: 120,
    strength: 0.008,
    duration: 3,
    target: 'player',
    maxLevel: 3,
    parameters: { affects: ['crystal'], travelSpeed: 260, falloff: 'constant' },
  },
  {
    id: 'ballistic_tunnel',
    name: 'Ballistic Tunnel',
    rarity: 'rare',
    tags: ['Gravity', 'Projectile', 'Velocity'],
    description:
      'Create a stationary directional field that bends only projectiles along your aim. Cross it freely while a volley changes course.',
    effect: 'field',
    mode: 'directional',
    energy: 20,
    cooldown: 7,
    radius: 230,
    strength: 0.007,
    duration: 4,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['Projectile'], falloff: 'constant' },
  },
  {
    id: 'shot_sink',
    name: 'Shot Sink',
    rarity: 'rare',
    tags: ['Gravity', 'Projectile', 'Control'],
    description:
      'Pull projectiles toward a decoy point without moving other bodies. Gather an incoming volley away from your escape path.',
    effect: 'field',
    mode: 'radial',
    energy: 18,
    cooldown: 6,
    radius: 300,
    strength: 0.009,
    duration: 3,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['Projectile'] },
  },
  {
    id: 'shot_stasis',
    name: 'Volley Stasis',
    rarity: 'rare',
    tags: ['Projectile', 'Control', 'Defense'],
    description:
      'Temporarily lock only projectiles near your aim. Released shots resist another lock; bodies remain free to move.',
    effect: 'lock',
    energy: 18,
    cooldown: 6,
    radius: 220,
    strength: 1,
    duration: 2,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['Projectile'] },
  },
  {
    id: 'seismic_cage',
    name: 'Seismic Cage',
    rarity: 'common',
    tags: ['Mass', 'Control', 'Defense'],
    description:
      'Lock stone bodies in place to make temporary physical barriers. Move through the gaps while other materials remain mobile.',
    effect: 'lock',
    energy: 18,
    cooldown: 7,
    radius: 230,
    strength: 1,
    duration: 3,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['stone'] },
  },
  {
    id: 'solar_system',
    name: 'Solar System',
    rarity: 'legendary',
    tags: ['Orbit', 'Mass', 'Gravity'],
    description:
      'Deploy three moving gravity bodies with alternating launch directions. All three positions need clearance; each body draws and spins nearby matter.',
    effect: 'planet',
    energy: 65,
    cooldown: 18,
    radius: 250,
    strength: 0.004,
    duration: 10,
    target: 'point',
    maxLevel: 3,
    parameters: { planetCount: 3 },
  },
  {
    id: 'repulsor_drone',
    name: 'Repulsor Drone',
    rarity: 'rare',
    tags: ['Machine', 'Gravity', 'Defense'],
    description:
      'Deploy a movable repulsion machine in open space. Push it into a crowd or keep it between your core and incoming matter.',
    effect: 'deploy',
    mode: 'radial',
    energy: 30,
    cooldown: 11,
    radius: 210,
    strength: -0.006,
    duration: 7,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'null_engine',
    name: 'Null Engine',
    rarity: 'epic',
    tags: ['Machine', 'Void', 'Control'],
    description:
      'Deploy a destructible machine that carries a zero-gravity bubble. Momentum survives inside the bubble; destroying the machine restores gravity.',
    effect: 'deploy',
    mode: 'zero',
    energy: 34,
    cooldown: 12,
    radius: 190,
    strength: 1,
    duration: 8,
    target: 'point',
    maxLevel: 3,
    parameters: { falloff: 'constant' },
  },
  {
    id: 'magnetic_relay',
    name: 'Magnetic Relay',
    rarity: 'rare',
    tags: ['Machine', 'Gravity', 'Metal'],
    description:
      'Deploy a machine whose attraction affects only metal. Reposition the source while stone and crystal remain outside its influence.',
    effect: 'deploy',
    mode: 'radial',
    energy: 24,
    cooldown: 10,
    radius: 260,
    strength: 0.007,
    duration: 8,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['metal'] },
  },
  {
    id: 'drift_bubble',
    name: 'Drift Bubble',
    rarity: 'rare',
    tags: ['Void', 'Movement', 'Control'],
    description:
      'Carry a small zero-gravity bubble around your core. Nearby matter keeps its momentum as you guide the bubble across the chamber.',
    effect: 'field',
    mode: 'zero',
    energy: 24,
    cooldown: 8,
    radius: 145,
    strength: 1,
    duration: 3,
    target: 'player',
    maxLevel: 3,
    parameters: { falloff: 'constant' },
  },
  {
    id: 'recoil_dash',
    name: 'Recoil Dash',
    rarity: 'common',
    tags: ['Movement', 'Velocity', 'Defense'],
    description:
      'Dash away from your aim with a brief shield. Aim toward the threat to retreat; a nearby gravity source increases the kick.',
    effect: 'dash',
    energy: 14,
    cooldown: 3,
    radius: 260,
    strength: -12,
    duration: 0,
    target: 'point',
    maxLevel: 3,
  },
  {
    id: 'implosive_pulse',
    name: 'Implosive Pulse',
    rarity: 'rare',
    tags: ['Gravity', 'Compression', 'Impact'],
    description:
      'Give nearby matter a single inward impulse toward your core. Set up a close-range launch or collision without leaving a persistent field.',
    effect: 'impulse',
    energy: 20,
    cooldown: 5,
    radius: 240,
    strength: -12,
    duration: 0,
    target: 'player',
    maxLevel: 3,
  },
  {
    id: 'gravity_rail',
    name: 'Gravitic Rail',
    rarity: 'rare',
    tags: ['Projectile', 'Velocity', 'Metal'],
    description:
      'Launch only metal matter along a narrow aiming line. Barrels and metal enemies become ammunition while stone cover stays put.',
    effect: 'beam',
    energy: 20,
    cooldown: 5,
    radius: 600,
    strength: 15,
    duration: 0,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['metal'] },
  },
  {
    id: 'traveling_vortex',
    name: 'Roaming Vortex',
    rarity: 'epic',
    tags: ['Orbit', 'Gravity', 'Velocity'],
    description:
      'Send a moving vortex along your aim. Its spinning center crosses the room, capturing and releasing different bodies as it travels.',
    effect: 'field',
    mode: 'vortex',
    energy: 32,
    cooldown: 9,
    radius: 160,
    strength: 0.007,
    duration: 3,
    target: 'player',
    maxLevel: 3,
    parameters: { travelSpeed: 240 },
  },
  {
    id: 'kinetic_mining',
    name: 'Kinetic Mining',
    rarity: 'common',
    tags: ['Mass', 'Impact', 'Control'],
    description:
      'Stop stone bodies near your aim, then launch them outward from that point. Rewrite a rock’s approach before using it as a weapon.',
    effect: 'impulse',
    energy: 18,
    cooldown: 5,
    radius: 210,
    strength: 12,
    duration: 0,
    target: 'point',
    maxLevel: 3,
    parameters: { affects: ['stone'], momentumScale: 0 },
  },
  {
    id: 'void_step',
    name: 'Void Step',
    rarity: 'rare',
    tags: ['Void', 'Movement', 'Defense'],
    description:
      'Your core alone ignores gravity for three seconds. Movement and momentum remain active, and collisions still hurt.',
    effect: 'response',
    energy: 20,
    cooldown: 7,
    radius: 1,
    strength: 0,
    duration: 3,
    target: 'player',
    maxLevel: 3,
    parameters: { selfOnly: true },
  },
];
