import type { AbilityDefinition } from './abilities';

const tether = (
  definition: Omit<AbilityDefinition, 'effect' | 'maxLevel' | 'target'>,
): AbilityDefinition => ({
  effect: 'tether',
  maxLevel: 3,
  target: 'point',
  ...definition,
});

export const tetherAbilities: AbilityDefinition[] = [
  tether({
    id: 'star_bind',
    name: 'Star Bind',
    rarity: 'rare',
    tags: ['Tether', 'Control', 'Mass'],
    description:
      'Connect up to four nearby bodies to the body nearest your aim. The central body becomes a shared hub that transfers motion to its satellites.',
    energy: 28,
    cooldown: 9,
    radius: 260,
    strength: 0.028,
    duration: 6,
    parameters: { chainTargets: 4, tetherLength: 110, tetherTopology: 'star' },
  }),
  tether({
    id: 'ring_bind',
    name: 'Ring Bind',
    rarity: 'epic',
    tags: ['Tether', 'Orbit', 'Control'],
    description:
      'Join three or four nearby bodies into a closed elastic loop, ordered by distance from your aim. Gravity deforms the entire loop; at least three bodies are required.',
    energy: 36,
    cooldown: 11,
    radius: 280,
    strength: 0.025,
    duration: 6,
    parameters: { chainTargets: 4, tetherLength: 100, tetherTopology: 'ring' },
  }),
  tether({
    id: 'towline',
    name: 'Towline',
    rarity: 'common',
    tags: ['Tether', 'Movement', 'Impact'],
    description:
      'Connect your core to the loose body nearest your aim for five seconds. Drag it into a collision or let a heavier body pull you.',
    energy: 18,
    cooldown: 6,
    radius: 260,
    strength: 0.025,
    duration: 5,
    parameters: { chainTargets: 2, tetherLength: 90, tetherPlayer: true },
  }),
  tether({
    id: 'core_train',
    name: 'Core Train',
    rarity: 'rare',
    tags: ['Tether', 'Movement', 'Mass'],
    description:
      'Lead a chain of up to three nearby bodies with your core. Each spring passes motion along the train, allowing the tail to sweep through enemies.',
    energy: 30,
    cooldown: 10,
    radius: 300,
    strength: 0.03,
    duration: 6,
    parameters: { chainTargets: 4, tetherLength: 75, tetherPlayer: true },
  }),
  tether({
    id: 'winch',
    name: 'Gravity Winch',
    rarity: 'rare',
    tags: ['Tether', 'Compression', 'Impact'],
    description:
      'Link two nearby bodies with a spring that contracts from 180 to 30 units over four seconds. Their mass and other forces determine how quickly they converge.',
    energy: 24,
    cooldown: 8,
    radius: 260,
    strength: 0.04,
    duration: 4,
    parameters: { chainTargets: 2, tetherLength: 180, tetherEndLength: 30 },
  }),
  tether({
    id: 'spreader',
    name: 'Gravity Spreader',
    rarity: 'rare',
    tags: ['Tether', 'Impact', 'Control'],
    description:
      'Link two nearby bodies with a spring that expands from 40 to 200 units over four seconds. Separate a cluster or push loose matter into opposite walls.',
    energy: 24,
    cooldown: 8,
    radius: 240,
    strength: 0.04,
    duration: 4,
    parameters: { chainTargets: 2, tetherLength: 40, tetherEndLength: 200 },
  }),
  tether({
    id: 'skyhook',
    name: 'Skyhook',
    rarity: 'common',
    tags: ['Tether', 'Control', 'Gravity'],
    description:
      'Suspend the loose body nearest your aim from a fixed point in open space for six seconds. The 80-unit spring lets gravity swing it around the anchor.',
    energy: 20,
    cooldown: 7,
    radius: 250,
    strength: 0.035,
    duration: 6,
    parameters: { chainTargets: 1, tetherLength: 80, tetherTopology: 'anchor' },
  }),
  tether({
    id: 'suspension',
    name: 'Suspension Array',
    rarity: 'epic',
    tags: ['Tether', 'Control', 'Defense'],
    description:
      'Attach up to three nearby bodies to one fixed point in open space. Damped springs form a suspended obstacle that gravity can still deform.',
    energy: 34,
    cooldown: 11,
    radius: 280,
    strength: 0.03,
    duration: 6,
    parameters: {
      chainTargets: 3,
      tetherLength: 120,
      tetherTopology: 'anchor',
      tetherDamping: 0.15,
    },
  }),
  tether({
    id: 'gravity_grapple',
    name: 'Gravity Grapple',
    rarity: 'rare',
    tags: ['Tether', 'Movement', 'Gravity'],
    description:
      'Connect your core to your aim in open space within 480 units. A contracting spring reels you toward the anchor while gravity bends your path; release after three seconds.',
    energy: 22,
    cooldown: 6,
    radius: 480,
    strength: 0.025,
    duration: 3,
    parameters: {
      chainTargets: 1,
      tetherLength: 180,
      tetherEndLength: 40,
      tetherTopology: 'anchor',
      tetherPlayer: true,
    },
  }),
];
